name: CI build for every commit
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 17
    - run: npm ci
    - run: npm run test:ci
    - run: npm run build:ci
